name: Build IconSwap

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fix permissions
        run: chmod -R +x .

      - name: Install xcodegen
        run: brew install xcodegen

      - name: Generate project
        run: xcodegen generate --use-cache

      - name: Debug files
        run: ls -R

      - name: List schemes
        run: xcodebuild -list

      - name: Build
        run: |
          xcodebuild \
            -project IconSwap.xcodeproj \
            -scheme IconSwap \
            -configuration Release \
            -sdk macosx \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: IconSwap
          path: build
