name: Build IconSwap

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install xcodegen
        run: brew install xcodegen

      - name: Generate project (force older format)
        run: xcodegen generate --spec project.yml

      - name: Downgrade project format
        run: |
          sed -i '' 's/objectVersion = 77;/objectVersion = 60;/g' IconSwap.xcodeproj/project.pbxproj

      - name: List schemes
        run: xcodebuild -list

      - name: Build
        run: |
          xcodebuild \
            -project IconSwap.xcodeproj \
            -scheme IconSwap \
            -configuration Release \
            -sdk macosx \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO
            SWIFT_VERSION=5.0
            
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: IconSwap
          path: build
