name: Build IconSwap

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install xcodegen
        run: brew install xcodegen

      - name: Generate project
        run: xcodegen generate

      - name: Force compatible project + Swift version
        run: |
          # Fix Xcode project format
          sed -i '' 's/objectVersion = 77;/objectVersion = 60;/g' IconSwap.xcodeproj/project.pbxproj
          
          # Force Swift 5 instead of Swift 6
          sed -i '' 's/SWIFT_VERSION = 6.0;/SWIFT_VERSION = 5.0;/g' IconSwap.xcodeproj/project.pbxproj

      - name: Build
        run: |
          xcodebuild \
            -project IconSwap.xcodeproj \
            -scheme IconSwap \
            -configuration Release \
            -sdk macosx \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: IconSwap
          path: build
